const app = document.querySelector('#app');

const shellTop = (label = 'PeachHacks') => `
  <div class="subpage-top"><a class="back" href="index.html">← Back to PeachHacks</a><span class="wordmark">${label}</span></div>`;

function home() {
  app.innerHTML = `<div class="site-shell">
    <header class="topline"><a class="wordmark" href="index.html">PeachHacks</a><div class="corner-links"><a href="auth.html">Sign in ↗</a><a href="sponsors.html">Sponsors ↗</a></div></header>
    <section class="hero"><div class="kicker">ColorStack presents · Atlanta, GA</div><h1>Build<br><span>something</span><br>peachy.</h1><div class="peach-orb" aria-hidden="true"></div><div class="hero-note"><p>A weekend for curious minds, bold ideas, and the people who make tech feel more like home. Bring a team, a sketch, or just yourself.</p><div class="register-card"><div class="stamp">Register here.</div><p>Applications open for PeachHacks 2025.</p><a class="button" href="auth.html">Get your spot →</a></div><div class="hero-date">OCT 17—19<small>Georgia State University</small></div></div></section>
    <section class="section light" id="about"><div class="section-head"><div><div class="eyebrow">01 / The why</div><h2>About<br>PeachHacks</h2></div><p>Not just a hackathon. A room full of fresh starts, late-night breakthroughs, and a whole lot of peach.</p></div><div class="about-grid"><h3>Make something useful. Make something weird. Make it yours.</h3><div class="about-copy"><p>PeachHacks is a beginner-friendly, community-powered hackathon hosted by <strong>ColorStack</strong>. Over one weekend, students and builders come together to learn out loud, turn ideas into prototypes, and meet the people they’ll build with next.</p><div class="fact-row"><div class="fact"><strong>48h</strong><span>of making</span></div><div class="fact"><strong>100+</strong><span>builders</span></div><div class="fact"><strong>∞</strong><span>good ideas</span></div></div></div></div></section>
    <section class="section" id="partners"><div class="section-head"><div><div class="eyebrow">02 / Good company</div><h2>Our<br>partners</h2></div><p>Know a team that believes in the next generation of builders? We’d love to meet them.</p></div><div class="partner-panel"><div class="partner-box"><span>Come make an impact with us.</span></div><div class="partner-box"><div class="tba">TBA ✦</div></div></div></section>
    <section class="section" id="schedule"><div class="schedule"><div class="schedule-intro"><div class="eyebrow">03 / The weekend</div><h2>Schedule</h2><p>Three days. A loose plan. Plenty of room for the good stuff.</p></div><div class="schedule-list"><div class="schedule-item"><time>FRI · 6:00 PM</time><strong>Check-in + welcome</strong><span>Find your people</span></div><div class="schedule-item"><time>FRI · 8:00 PM</time><strong>Opening ceremony</strong><span>Let’s begin</span></div><div class="schedule-item"><time>SAT · 9:00 AM</time><strong>Workshops + hacking</strong><span>Make the thing</span></div><div class="schedule-item"><time>SAT · 7:00 PM</time><strong>Dinner + demos</strong><span>Share the progress</span></div><div class="schedule-item"><time>SUN · 2:00 PM</time><strong>Judging + closing</strong><span>Big finish</span></div></div></div></section>
    <section class="section light" id="faq"><div class="section-head"><div><div class="eyebrow">04 / The fine print</div><h2>FAQ</h2></div><p>Questions are good. Here are a few answers to get you moving.</p></div><div class="faq-list">${faq('Who can participate?', 'PeachHacks is open to all current students. You do not need prior hackathon experience or a polished idea—just curiosity and a willingness to learn.')}${faq('Do I need a team?', 'Nope. Come solo and we’ll help you find collaborators during team formation, or bring a few friends and build together.')}${faq('What should I bring?', 'Your laptop, charger, student ID, and anything that helps you feel at home. We’ll handle food, snacks, Wi-Fi, mentors, and the good vibes.')}${faq('What does it cost?', 'Nothing. PeachHacks is completely free for participants, thanks to the ColorStack community and our partners.')}</div></section>
    <footer class="footer"><span>PeachHacks · Hosted by ColorStack</span><a href="auth.html">Register for 2025 ↗</a></footer>
  </div>`;
  document.querySelectorAll('.faq button').forEach(btn => btn.addEventListener('click', () => btn.parentElement.classList.toggle('open')));
}
function faq(q, a) { return `<div class="faq"><button aria-expanded="false">${q}<span>+</span></button><div class="faq-answer"><p>${a}</p></div></div>`; }
function auth() { app.innerHTML = `<div class="subpage">${shellTop('ColorStack × PeachHacks')}<div class="subpage-content"><div class="eyebrow">Participant portal</div><h1>Save your<br>seat.</h1><p>Sign in to register for PeachHacks, update your team, and keep all your weekend details in one place.</p><form class="auth-form"><div class="field"><label for="email">School email</label><input id="email" type="email" placeholder="you@school.edu" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" placeholder="••••••••" required></div><button class="button" type="submit">Sign in →</button><div class="form-note"></div></form></div></div>`; formMessage(); }
function sponsors() { app.innerHTML = `<div class="subpage">${shellTop('PeachHacks / Partners')}<div class="subpage-content"><div class="eyebrow">Build with us</div><h1>Put your name<br>on the future.</h1><p>PeachHacks gives your team a direct line to a new generation of builders, thinkers, and collaborators. Partner with us to support access and meet the people shaping what’s next.</p><form class="auth-form"><div class="field"><label for="company">Company name</label><input id="company" placeholder="Your company" required></div><div class="field"><label for="contact">Work email</label><input id="contact" type="email" placeholder="hello@company.com" required></div><button class="button" type="submit">Start a conversation →</button><div class="form-note"></div></form></div><div class="sponsor-grid"><div>Community partner</div><div>Workshop partner</div><div>Food + good vibes</div></div></div>`; formMessage(); }
function formMessage() { document.querySelector('form').addEventListener('submit', e => { e.preventDefault(); document.querySelector('.form-note').textContent = 'Thanks — we’ll be in touch soon ✦'; }); }
const page = location.pathname.split('/').pop();
page === 'auth.html' ? auth() : page === 'sponsors.html' ? sponsors() : home();
